import api from './api';

/* eslint-disable */
export async function  AutoGeneratedCode(type) {
    api.post('/commonApi/getCodeValue',{type}).then((res) => {
        return res.data.data
      }).catch(()=>{
        return ''
      });
};
